/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.app.kafka.producer.SampleDataProducer;

public class App {
    public static void main(String[] args) {
        //System.out.println("hello");

        SampleDataProducer test = new SampleDataProducer(); 

        try{
            test.testKafka();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }

    }
}
